/*
 * This source file was generated by the Gradle 'init' task
 */
package design.patterns;


import design.patterns.singleton.SingletonDPOne;
import design.patterns.singleton.SingletonDPTwo;

public class App {
    
    public static void main(String[] args) {

        // SingletonDPOne singletonDPOne = SingletonDPOne.getSingletonDPOne();
        // System.out.println(singletonDPOne.hashCode());
        // SingletonDPOne singletonDPOneq = SingletonDPOne.getSingletonDPOne();
        // System.out.println(singletonDPOneq.hashCode());

        // SingletonDPTwo singletonDPTwo = SingletonDPTwo.getSingletonDPTwo();
        // System.out.println(singletonDPTwo.hashCode());
        // SingletonDPTwo singletonDPTwoq = SingletonDPTwo.getSingletonDPTwo();
        // System.out.println(singletonDPTwoq.hashCode());

    }
}
